# 使得/token不需要验权
management:
  security:
    enabled: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    # 服务列表缓存更新时间
    registryFetchIntervalSeconds: 10
    serviceUrl:
      defaultZone: ${grimlock_eureka_serviceUrl:http://grimlock:abc123456@localhost:8761/eureka/}
  instance:
    preferIpAddress: true
    # 心跳间隔
    leaseRenewalIntervalInSeconds: 10

spring:
  application:
    name: uaa-service
  cloud:
    config:
      discovery:
        # 使用eureka发现配置中心服务
        enabled: true
        # 配置中心服务名称
        serviceId: config-server
      # 登录用户名和密码
      username: ${grimlock_config_server_security_name:grimlock}
      password: ${grimlock_configserver_security_password:12345678}
      # 覆盖本地配置
      overrideNone: false
      failFast: true