# 上下文初始化加载
info:
  name: grimlock-admin-server

server:
  port: 8080

# 配置eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://scl:abc123456@localhost:8761/eureka
  instance:
      preferIpAddress: true
      # 心跳间隔
      leaseRenewalIntervalInSeconds: 10

# 开启熔断机制,不然不会生效fallback = FeignSmsMvcClientFailback.class
feign:
  hystrix:
    enabled: true


########hystrx相关配置.
hystrix:
  threadpool:
    # 指定服务的配置
    grimlock-sms-server:
      coreSize: 1
      maxQueueSize: 200
      queueSizeRejectionThreshold: 3
    # 这是默认的配置
    default:
      coreSize: 1
      maxQueueSize: 200
      queueSizeRejectionThreshold: 2
  command:
    # 指定feign客户端中具体的方法(基本上不会单独去配置)
    FeignSmsClient#timeout():
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
    # 这是默认的配置
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 1000
            interruptOnTimeout: true
            interruptOnFutureCancel: false
          semaphore:
            maxConcurrentRequests: 2
      fallback:
        enabled: true
        isolation:
          semaphore:
            maxConcurrentRequests: 10
      circuitBreaker:
        enabled: true
        forceOpen: false
        forceClosed: false
        requestVolumeThreshold: 3
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 10000
      metrics:
        rollingStats:
          timeInMilliseconds: 5000
          numBuckets: 10
        rollingPercentile:
          enabled: true
          timeInMilliseconds: 60000
          numBuckets: 6
          bucketSize: 100
        healthSnapshot:
          intervalInMilliseconds: 500


